[package]
name = "proxy-rewriter"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
base64.workspace = true
http.workspace = true
regex.workspace = true
url.workspace = true
